on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 25 13 * * *
name: Semgrep
jobs:
  semgrep-daily:
    name: Daily Semgrep SAST full repo scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    strategy:
      matrix:
        # See https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix
        # Semgrep cannot handle scanning the full repo it returns 5xx errors
        glob: ["app/[a-e]*/**", "app/[f-j]*/**", "app/[k-o]*/**", "app/[p-t]*/**", "app/[u-z]*/**"]
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      # Note, intentionally no ref argument here, so checkout action will use the Default branch
      - uses: actions/checkout@v4
      - run: |
          export SEMGREP_REPO_DISPLAY_NAME="${{ matrix.glob }}"
          semgrep ci --code --include="${{ matrix.glob }}"

